//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basket.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BasketMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasketMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basket.Resources.BasketMessages", typeof(BasketMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basket for user &quot;{0}&quot; was not found..
        /// </summary>
        internal static string BasketNotFound {
            get {
                return ResourceManager.GetString("BasketNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basket item with product ID &quot;{0}&quot; was not found..
        /// </summary>
        internal static string BasketItemNotFound {
            get {
                return ResourceManager.GetString("BasketItemNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item quantity must be greater than zero..
        /// </summary>
        internal static string QuantityMustBePositive {
            get {
                return ResourceManager.GetString("QuantityMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basket for user &quot;{0}&quot; was checked out successfully..
        /// </summary>
        internal static string BasketCheckedOut {
            get {
                return ResourceManager.GetString("BasketCheckedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basket for user &quot;{0}&quot; was cleared successfully..
        /// </summary>
        internal static string BasketCleared {
            get {
                return ResourceManager.GetString("BasketCleared", resourceCulture);
            }
        }
    }
}
