//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrdersMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orders.Resources.OrdersMessages", typeof(OrdersMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order with ID &quot;{0}&quot; was not found..
        /// </summary>
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order &quot;{0}&quot; was created successfully..
        /// </summary>
        internal static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order &quot;{0}&quot; was cancelled successfully..
        /// </summary>
        internal static string OrderCancelled {
            get {
                return ResourceManager.GetString("OrderCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer ID is required..
        /// </summary>
        internal static string CustomerIdRequired {
            get {
                return ResourceManager.GetString("CustomerIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one order item is required..
        /// </summary>
        internal static string OrderItemsRequired {
            get {
                return ResourceManager.GetString("OrderItemsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid order status transition from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidOrderStatus {
            get {
                return ResourceManager.GetString("InvalidOrderStatus", resourceCulture);
            }
        }
    }
}
